delay = 60
message = """
{{.Url}}
{{.Title}}
{{.Format}} with price {{.Price}} (postage {{.Postage}})
Condition {{.Condition}}
Seller has {{.SellerStars}} stars with a rating of {{.SellerFeedbackPercentage}}%
"""

web-server = false
track-scraped-urls = true

[[searches]]
url = ""